### ISSUE TITLE
kubectl check error

### ISSUE THREAD

**Issue by uglyliu** [lework/kubectl-check#1]
大佬，K8s版本：1.20.4，偶尔会出现以下报错，这个可能是版本有些信息不一致导致的？

See 'kubectl get -h' for help and examples
error: --raw must be a valid URL path: parse "null/scale": invalid URI for request
See 'kubectl get -h' for help and examples
error: --raw must be a valid URL path: parse "null/scale": invalid URI for request
See 'kubectl get -h' for help and examples
error: --raw must be a valid URL path: parse "null/scale": invalid URI for request
See 'kubectl get -h' for help and examples
error: --raw must be a valid URL path: parse "null/scale": invalid URI for request
See 'kubectl get -h' for help and examples
jq: error (at <stdin>:13704): Cannot iterate over null (null)

**Comment by uglyliu** [comment]
问题找到了，K8s1.20以上的版本Pod信息中selfLink这个字段没了，导致取不到值，96行我写死了
local deploy_sel=$($kubectl get --raw "/apis/apps/v1/namespaces/$namespace/deployments/$deploy_name/scale" | jq -r .status.targetSelector)

**Comment by lework** [comment]
好的，最近太忙了，感谢指出问题。
